name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
          cache: maven
      - name: Build client
        run: mvn -B package --file client/pom.xml
      - name: Build server
        run: mvn -B package --file server/pom.xml
